# Generated by Django 4.0.2 on 2023-02-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_rename_authority_order_zarin_authority'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='zarin_data',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='zarin_ref_id',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
