# Generated by Django 4.0.2 on 2023-01-17 12:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_image_alter_product_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='datetime_create',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 17, 12, 1, 17, 728974, tzinfo=utc), verbose_name='Time Created'),
        ),
    ]
