# Generated by Django 4.0.2 on 2023-01-30 07:25

import ckeditor.fields
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_comment_datetime_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='datetime_create',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 30, 7, 25, 53, 898951, tzinfo=utc), verbose_name='Time created'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Comment Text'),
        ),
        migrations.AlterField(
            model_name='product',
            name='datetime_create',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 30, 7, 25, 53, 898099, tzinfo=utc), verbose_name='Time Created'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Description'),
        ),
    ]
