# Generated by Django 4.0.2 on 2023-01-30 08:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_comment_datetime_create_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='datetime_create',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 30, 8, 25, 18, 367215, tzinfo=utc), verbose_name='Time created'),
        ),
        migrations.AlterField(
            model_name='product',
            name='datetime_create',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 30, 8, 25, 18, 366268, tzinfo=utc), verbose_name='Time Created'),
        ),
    ]
