# Generated by Django 4.0.2 on 2023-01-30 08:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_comment_datetime_create_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='short_description',
        ),
        migrations.AlterField(
            model_name='comment',
            name='datetime_create',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 30, 8, 46, 37, 768974, tzinfo=utc), verbose_name='Time created'),
        ),
        migrations.AlterField(
            model_name='product',
            name='datetime_create',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 30, 8, 46, 37, 767651, tzinfo=utc), verbose_name='Time Created'),
        ),
    ]
