# Generated by Django 4.0.2 on 2023-02-06 13:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_comment_datetime_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='datetime_create',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 6, 13, 48, 4, 746403, tzinfo=utc), verbose_name='Time created'),
        ),
        migrations.AlterField(
            model_name='product',
            name='datetime_create',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 6, 13, 48, 4, 745531, tzinfo=utc), verbose_name='Time Created'),
        ),
    ]
